### ISSUE TITLE
Caption button doesn't work after being activated and deactivated

### ISSUE THREAD

**Issue by fredericpfisterer** [ghinda/acornmediaplayer#12]
I observed the problem when there is only on caption track.

I found the probleme and corrected it but I don't know how I can upload the code.

**Comment by ghinda** [comment]
Hey!
The easiest way would be to tell me what you changed in the code to fix it, and I'll do the changes myself.

The other way would be to fork this repository, make the changes in a separate branch, and make a pull request to my repository: http://stackoverflow.com/questions/4384776/how-do-i-contribute-to-others-code-in-github

**Comment by ghinda** [comment]
Along the fixes in your pull request, I also added another fix, so the captions should now work ok for both a single `track` or multiple.
