### ISSUE TITLE
integration with webshim polyfill

### ISSUE THREAD

**Issue by aFarkas** [ghinda/acornmediaplayer#14]
Hi,

I made a version of acornmediaplayer which works with the webshim mediaelement polyfill. Basically it now also supports IE7/8 (CSS issues aren't fixed). You can have a look https://github.com/aFarkas/acornmediaplayer/tree/development.

Additionally youtube videos can be loaded in all modern browsers. And for all flash supporting browsers flv, mp4 and streaming is also supported.

The changes are esspecially about how to access properties (i.e.: $.prop(this, 'buffered') instead of this.buffered). If you want to take it, i would make a PR.

regards
alex

**Comment by ghinda** [comment]
That sounds great! Send me the pull request and I'll definitely merge it in.

**Comment by aFarkas** [comment]
ping @ghinda 

Do you have any questions. Want any changes? For this PR?

**Comment by ghinda** [comment]
Hey, sorry about the delay. I haven't had any free time to look over this yet, but I'll try to look over it this weekend.

**Comment by ghinda** [comment]
I've merged the PR, awesome work! Thanks a lot!
