### ISSUE TITLE
Unable to play anything on Firefox 30.0 on Ubuntu

### ISSUE THREAD

**Issue by franck-grenier** [ghinda/acornmediaplayer#17]
Hello,
I'm trying to use Acorn Media Player on Firefox 30.0 on Ubuntu but nothing on your demo page plays for me. It's ok in Chrome on Ubuntu.

**Comment by ghinda** [comment]
It seems to be working fine on my end. Testing on Kubuntu 14.04 and Firefox 30.0.

It was probably an issue with Heroku, where the media files are hosted.
Could you take another look? http://ghinda.net/acornmediaplayer/

If it still doesn't work, do you have the `ubuntu-restricted-extras` package installed?

**Comment by franck-grenier** [comment]
Hi,
I installed ubuntu-restricted-extras package but it still doesn't work.

I'm able to play the video with the browser default controls. But the controls provided by Acorn Media Player do not work.

I'm getting 2 Javascript errors : 
- set the mime-type of your WebVTT files to text/vtt. see: http://dev.w3.org/html5/webvtt/#text/vtt
  http://afarkas.github.io/webshim/js-webshim/minified/polyfiller.js
  Line 1
- please use WebVTT format. This is the standard
  http://afarkas.github.io/webshim/js-webshim/minified/polyfiller.js
  Line 1
