### ISSUE TITLE
Slider progress bar not working on Safari

### ISSUE THREAD

**Issue by salientnet** [ghinda/acornmediaplayer#19]
Hi,

I am using the Audio/Video player and it is good.
But when I am playing the audio on Safari, it is not working nothing.
Please help me quickly.

Regards,
Salient

**Comment by ghinda** [comment]
I can't replicate the issue you're having.

I tested https://ghinda.net/acornmediaplayer/demos.html on Safari `10.0.1`, and everything seems to be ok, for both audio and video files.

Can you make a http://jsbin.com/ demo that shows your issue?

**Comment by salientnet** [comment]
Hi Ghinda,

Thanks for your reply.
right, I tested the demos.html too. But it is not working on our platform.
Please check www.ktbyte.com/intro and let me know the issue what it is.

Regards,
Salient

**Comment by ghinda** [comment]
Sorry, I can't help with debugging your app. You should try posting the issue on https://stackoverflow.com.

If you can isolate the issue in a small http://jsbin.com/ demo, I'll take another look.
Closing for now.

**Comment by salientnet** [comment]
I didn't fix the slider progress bar issue yet.
could you check the line 479 of the acornmediaplayer.js file?
just var max = parseInt(acorn.$self.prop('duration'), 10);
it don't get the max value on safari.
looking forward to hearing from you.
