### ISSUE TITLE
Firefox duplicate video

### ISSUE THREAD

**Issue by ghost** [ghinda/acornmediaplayer#5]
In firefox, using this plugin seems to make a duplicate of the video, that plays offscreen at the same time as the visible video (I hit pause and still hear the background video playing). Even if I remove the original video from the dom, it keeps playing. No issue on chrome. Any idea what's up?

**Comment by ghost** [comment]
Note, this is only noticable with autoplay="auto" on the video tag. I don't know if it solves the underlying problem, though.

**Comment by ghinda** [comment]
That's odd.. Can you make a JsFiddle example with this issue?

**Comment by ghinda** [comment]
There seems to be a jQuery/Firefox issue that others have encountered as well.
http://bugs.jquery.com/ticket/9174

I'll include a fix for it, so that you can use autoplay with the media player.
