### ISSUE TITLE
Fullscreen on Firefox

### ISSUE THREAD

**Issue by andreas83** [ghinda/acornmediaplayer#6]
I noticed that goFullscreen() does not support mozillas fullscreen api,
my quick hack was to add 

if(acorn.$self[0].webkitSupportsFullscreen) {
    acorn.$self[0].webkitEnterFullScreen();
} else if(acorn.$self[0].mozRequestFullScreen){
     acorn.$self[0].mozRequestFullScreen();
}

maybe there is a better solution, but so far it fits my needs.

thanks for this great project

**Comment by ghinda** [comment]
I didn't know Firefox supported the Full Screen API with the prefix.
I'll add support for it soon. Thanks for the report!

**Comment by ghinda** [comment]
I've just added support for the standard Fullscreen API. This includes Firefox and Opera, beside the other Webkit browsers that were already supported.

Make sure to get the latest version, it also includes some new improvements.
