### ISSUE TITLE
Poster on pause

### ISSUE THREAD

**Issue by Tusko** [ghinda/acornmediaplayer#7]
Hello! I need to show poster when video is paused. How I can do this?

**Comment by Tusko** [comment]
In HTML before video I'm added:

<img class="posterize" src="/somepath/poster.jpg" />
<div class="acorn-hidden-play">

CSS
figure {margin: 0;cursor: pointer; position: relative;}
video, .posterize{
    max-width: 100%;
    height: auto;
}

.posterize, .acorn-hidden-play {
    position: absolute;
    top: 0;
    left: 0;
    z-index: 8040;
    background:#000;
    display: none
    }

.acorn-hidden-play {
    background: none repeat scroll 0 0 transparent !important;
    clear: both;
    content: "";
    display: block;
    z-index: 9;
}

JS
function videoposter(){
    var p = $('.posterize'); //poster
        v = $('video'); //video tag
        t = $('.acorn-hidden-play'); //hidden play/pause button
        pl = $('.acorn-play-button'); //original playubutton
        ss = $('.acorn-seek-slider'); //seek slider
        h = p.height(); //poster height
        w = p.width(); //poster width
        v.css({'height':h, 'width':w}); //set poster size to video size
        t.css({'height':h, 'width':w}); set poster size to hidden play/pause button

```
t.bind('click', function(){
    pl.click();
    p.fadeIn(500);
    ss.fadeOut(500);
});

p.bind('click', function(){
    pl.click();
    p.fadeOut(500);
    ss.fadeIn(500);
});
}
```

INIT

var v = document.getElementsByTagName("video")[0];
    v.addEventListener("loadedmetadata", function() { videoposter(); $(window).trigger("resize"); }, true);

Try to add this option in Your script ;)

**Comment by ghinda** [comment]
It's not really a standard feature of most players, web or desktop, so I'm not going to implement this right now, but thanks for the idea.
